policySets: []
# providers:
  # - name: ActiveDirectory
  #   metadataDocument: iam-providers/active-directory.xml
roleSets:
  - deploymentTargets:
      organizationalUnits:
        - Root
    roles:
      - name: EC2-Default-SSM-AD-Role
        instanceProfile: true
        assumedBy:
          - type: service
            principal: ec2.amazonaws.com.cn
        policies:
          awsManaged:
            - AmazonSSMManagedInstanceCore
            - AmazonSSMDirectoryServiceAccess
            - CloudWatchAgentServerPolicy
        boundaryPolicy: Default-Boundary-Policy
      # - name: SecurityAuditors
      #   assumedBy:
      #     - type: provider
      #       principal: ActiveDirectory
      #   policies:
      #     awsManaged:
      #       - SecurityAudit
      #   boundaryPolicy: Default-Boundary-Policy
groupSets: []
userSets: []